name: Scheduled Deploy

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy hook request
        run: curl -X POST -d {} ${{ secrets.DEPLOY_HOOK }}
